# Generated by Django 6.0.5 on 2026-06-16 09:59
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_post_title'),
    ]

    operations = [
        TrigramExtension(),
    ]
