# Generated by Django 6.0.5 on 2026-06-20 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20260616_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='Blog.post')),
            ],
            options={
                'unique_together': {('post', 'ip_address')},
            },
        ),
    ]
